[features]
seeds = true

[programs.mainnet]
coral_multisig = "86A3SjX2cdavMiAhipoZGbVmKq8Tbari4g3pc9iAqWL"

[programs.devnet]
coral_multisig = "86A3SjX2cdavMiAhipoZGbVmKq8Tbari4g3pc9iAqWL"

[programs.localnet]
coral_multisig = "86A3SjX2cdavMiAhipoZGbVmKq8Tbari4g3pc9iAqWL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id2.json"

[scripts]
test = "npx mocha -t 1000000 tests/"
